# -*- coding: utf-8 -*-
"""No.2-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWxSedl9LsMEocoDbLDR2Kh0z1dqneW5
"""

h = float( input ("身長を入力してください:"))
w = float( input ("体重を入力してください"))
s = int( input("男性なら１を女性なら２を男女共用の場合は１，２以外を入力してください"))
if s==1: avBMI = 22
if s==2: avBMI = 21
else : avBMI = 21.5
avw = h * h * avBMI
himan = w /avw - 1
himan *= 100
print(f'標準体重は{avw}です')
print(f'肥満度は{himan}です')
if himan >= 10 : print("太りすぎ")
elif himan <= -10 : print("痩せすぎ")
else : print("標準")

h = float( input ("身長を入力してください:"))
w = float( input ("体重を入力してください"))
s = int( input("男性なら１を女性なら２を男女共用の場合は１，２以外を入力してください"))
if s==1: avBMI = 22
if s==2: avBMI = 21
else : avBMI = 21.5
avw = h * h * avBMI
himan = w /avw - 1
himan *= 100
print(f'標準体重は{avw}です')
print(f'肥満度は{himan}です')
if himan >= 10 : print("太りすぎ")
elif himan <= -10 : print("痩せすぎ")
else : print("標準")

h = float( input ("身長を入力してください:"))
w = float( input ("体重を入力してください"))
s = int( input("男性なら１を女性なら２を男女共用の場合は１，２以外を入力してください"))
if s==1: avBMI = 22
if s==2: avBMI = 21
else : avBMI = 21.5
avw = h * h * avBMI
himan = w /avw - 1
himan *= 100
print(f'標準体重は{avw}です')
print(f'肥満度は{himan}です')
if himan >= 10 : print("太りすぎ")
elif himan <= -10 : print("痩せすぎ")
else : print("標準")

h = float( input ("身長を入力してください:"))
w = float( input ("体重を入力してください"))
s = int( input("男性なら１を女性なら２を男女共用の場合は１，２以外を入力してください"))
if s==1: avBMI = 22
if s==2: avBMI = 21
else : avBMI = 21.5
avw = h * h * avBMI
himan = w /avw - 1
himan *= 100
print(f'標準体重は{avw}です')
print(f'肥満度は{himan}です')
if himan >= 10 : print("太りすぎ")
elif himan <= -10 : print("痩せすぎ")
else : print("標準")

h = float( input ("身長を入力してください:"))
w = float( input ("体重を入力してください"))
s = int( input("男性なら１を女性なら２を男女共用の場合は１，２以外を入力してください"))
if s==1: avBMI = 22
if s==2: avBMI = 21
else : avBMI = 21.5
avw = h * h * avBMI
himan = w /avw - 1
himan *= 100
print(f'標準体重は{avw}です')
print(f'肥満度は{himan}です')
if himan >= 10 : print("太りすぎ")
elif himan <= -10 : print("痩せすぎ")
else : print("標準")

h = float( input ("身長を入力してください:"))
w = float( input ("体重を入力してください"))
s = int( input("男性なら１を女性なら２を男女共用の場合は１，２以外を入力してください"))
if s==1: avBMI = 22
if s==2: avBMI = 21
else : avBMI = 21.5
avw = h * h * avBMI
himan = w /avw - 1
himan *= 100
print(f'標準体重は{avw}です')
print(f'肥満度は{himan}です')
if himan >= 10 : print("太りすぎ")
elif himan <= -10 : print("痩せすぎ")
else : print("標準")