# -*- coding: utf-8 -*-
"""No2-ad2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WfyMryJY4XPkW8EurjY-NB1H76JUOJCc
"""

x = int(input('二進数に直したい自然数を入力してください'))
list = []
while x>0:
   list.append( x % 2)
   x = x // 2
list.reverse()
L = [str(a) for a in list]
L = "".join(L)
print(L)