# -*- coding: utf-8 -*-
"""No.2-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rXrKQwcCytw57xfYScbA-ZghDbP-BN1u
"""

x = int( input ("Input number:"))
if (x<0):
   y = x
   x = -x
n = 1
sa = 1
ans = 1
while sa > 0.0000001:
   sa *= x / n
   n += 1
   ans += sa
if (y<0) :
  ans = 1 / ans
  print(round(ans,8))
else : print (round(ans,8))

x = int( input ("Input number:"))
if (x<0):
   y = x
   x = -x
else:
  y=x
n = 1
sa = 1
ans = 1
while sa >= 0.0000001:
   sa *= x / n
   n += 1
   ans += sa
if (y<0) :
  ans = 1 / ans
  print(round(ans,8))
else : print (round(ans,8))

x = int( input ("Input number:"))
if (x<0):
   y = x
   x = -x
else:
  y=x
n = 1
sa = 1
ans = 1
while sa >= 0.0000001:
   sa *= x / n
   n += 1
   ans += sa
if (y<0) :
  ans = 1 / ans
  print(round(ans,8))
else : print (round(ans,8))