# -*- coding: utf-8 -*-
"""No.2 ad1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181Q2ZGtIOJLU69-ASZ7Xj6zS6OAYVGOe
"""

num = input("10個の数を入力してください")
numlist = num.split()
numlist = [int(number) for number in numlist]
for a in range(0,9):
 for i in range(0,9):
   if numlist[i+1]<numlist[i] :
     x= numlist[i+1]
     numlist[i+1] = numlist[i]
     numlist[i] = x
 a +=1
print('最小値は', numlist[0],'であります')
print('最小値は',numlist[9],'だよ')