# -*- coding: utf-8 -*-
"""No.2-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13hFZXPPbPpl0oZ-tTNEaFLyaubBcFToP
"""

print("九九の掛け算で24になる 2 つの数字の組み合わせは以下の通り")
for i in range(1,9):
  if 24%i==0:
     j=24//i
     if 1<=j<10:print(i,j)