# -*- coding: utf-8 -*-
"""No.2 -1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ffX5vuufaMHArTEcKlvwLZlrNYIU42N7
"""

def fact(n:int)->int:
  fact=1
  if n<0:
    print("エラー:nの値が負です!!")
  else:
    while n > 1:
     fact = fact * n
     n = n - 1
    return fact

 fact(10)

fact(0)

fact(-3)