# -*- coding: utf-8 -*-
"""No3-ad1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEfK0-y606RTsO2fNKuJ5rKVPEBtT8f1
"""

def mymax1():
  if x>y:
    print(x)
  if y>x:
    print(y)

def mymax2():
  if x>y:
    print(x)
  else:
    print(y)

def mymax3():
 print( x * (x >= y) + y * (y > x))

x=input("x:")
y=input("y:")
mymax1()
mymax2()
mymax3()