# -*- coding: utf-8 -*-
"""No3-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uX7O81DWIxZ-w3vqEVrxMwvEsR0XaGU-
"""

def fn(x):
  n=1
  result = 0
  while n<=x:
    result += n*n
    n += 1
  return result

x = int( input("n=:"))
print(fn(x))

x = int( input("n=:"))
print(fn(x))

x = int( input("n=:"))
print(fn(x))

x = int( input("n=:"))
print(fn(x))

x = int( input("n=:"))
print(fn(x))

x = int( input("n=:"))
print(fn(x))

x = int( input("n=:"))
print(fn(x))