# -*- coding: utf-8 -*-
"""No.3-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wPQo5XTOtldGlIL5wAf6kF3Rxh2xWs0W
"""

import math
def main():
  x1 = int(input("x1:"))
  y1 = int(input("y1:"))
  z1 = int(input("z1:"))
  x2 = int(input("x2:"))
  y2 = int(input("y2:"))
  z2 = int(input("z2:"))

  zahyou1 = (x1,y1,z1)
  zahyou2 = (x2,y2,z2)
  cos = inseki(zahyou1[0],zahyou2[0],zahyou1[1],zahyou2[1],zahyou1[2],zahyou2[2]) / ((vec(zahyou1[0],zahyou1[1],zahyou1[2])) * (vec(zahyou2[0],zahyou2[1],zahyou2[2])))
  acos = math.acos(cos)
  print(rad(acos))
def vec(x,y,z):
  vec = math.sqrt(x**2 + y**2 + z**2)
  return vec
def inseki(x,y,z,p,q,r):
  inseki = x*y + z*p + q*r
  return inseki
def rad(raj):
  deg = raj * 180 / math.pi
  return deg


main()

main()