# -*- coding: utf-8 -*-
"""No3-ad2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13O3Yh-yfYslDgLq3MoNvIFWXdCzZmoyM
"""

list=[76,98,80,69,49,88,71,66,82,100]
for i in range(0,9):
  a=str(i+1)
  print(a+"人目の成績は")
  if list[i+1]>=90:
    print("Sです")
  elif list[i+1]>=80:
    print("Aです")
  elif list[i+1]>=70:
    print("Bです")
  elif list[i+1]>=60:
   print("Cです")
  elif list[i+1]<=59:
   print("Fです")