# -*- coding: utf-8 -*-
"""ex04_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1TCVPBnn2Dd1oUW7gLCD2jkcIF5P5U8
"""

f = open("Coll_of_ES.txt","w")
f.write("""Yokohama National University
College of Engineering Science
Department of Mathematics, Physics, Electrical Engineering and Computer Science""")
f.close
f=open("Coll_of_ES.txt","r")
text = f.read()
f.close
print(text)

!ls -l

def file_copy(ffile,gfile):
 f = open(ffile,"r")
 g = open(gfile,"w")
 import shutil
 shutil.copy2(ffile,gfile)
 f.close()
 g.close()

def main():
 ffile=input("input source file name:")
 gfile=input("input target file name:")
 a=input("copy from " + str(ffile)+ "to"+ str(gfile)+" ,ok?(y/n):")
 if a == "y":
  file_copy(ffile,gfile)

main()

f = open("copy1.txt","r")
text = f.read()
f.close
print(text)

ls -l