# -*- coding: utf-8 -*-
"""No.4-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JetQt-OHuvo9UbKP_DCbJjQsVk2dZF55
"""

def key_input():
 print("文字列を入力してください:")
 while True:
  try:
    a=input("")
    list.append(a)
  except EOFError:
    break

def main():
  key_input()
  print("入力れた各行は以下の通り：")
  for i, line in enumerate(list):
    print("{:d}".format(i+1) +" "+ line)

list=[]
main()