# -*- coding: utf-8 -*-
"""ex04_a3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXNWEL0JH7_pfiLRxluYytdJ0a7MLgkR
"""

import csv
import random
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0.01, 1.01, 0.01)
rows = 100
cols = 10
list2 = [[0 for j in range(cols)] for i in range(rows)]

for k in range (1, 10):
  for i in range (0, 999):
    result = 0
    for j in range (0, k):
     result += random.uniform(0, 1)
    result = round(result / (k), 2)
    for p in range (0, 100):
     if p/100 <= result < (p+1)/100:
        list2[p][k-1] += 1
for i in range (0, 100):
   print(round ((i+1) * 0.01, 2), end=' ')
   for j in range (0, 9):
    print(list2[i][j], end=', ')
   print()

for j in range(9):
    y = [list2[i][j] for i in range(100)]
    plt.bar(x, y, width=0.01, label=f'k={j+1}', alpha=0.7)

plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Bar Chart of list2')
plt.legend()
plt.show()

with open('output.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Value", "Count1", "Count2", "Count3", "Count4", "Count5", "Count6", "Count7", "Count8", "Count9"])
    for i in range (0, 100):
        row = [round ((i+1) * 0.01, 2)]
        for j in range (0, 9):
            row.append(list2[i][j])
        writer.writerow(row)