# -*- coding: utf-8 -*-
"""ex04_a2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KtUrSvK1VeAXrsruOZXXaN0ShmaRk-Rc
"""

f = open("sample_1.py","w")
f.write("""import sys
print ( sys.stdin.read() )""")
f.close()

!cat sample_1.py

def main():
 File =  input("ファイル名を入力してください：")
 f = open(str(File),"r")
 lines = f.readlines()
 f.close()
 sentence = 0
 word = 0
 char = 0
 for i,line in enumerate(lines):
  sentence += 1
  word += len([character for character in line if character.isalpha()])
  char += len(line.split())

 print("行数:"+str(sentence))
 print("文字数:"+str(word)+"バイト")
 print("単語数:"+str(char))

main()