# -*- coding: utf-8 -*-
"""ex04_3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vp9ExFGNsaGFFT2PTpMX_qOV2WFfoeV
"""

f = open("test1.txt","w")
f.write("""A - B - C - D - E - F - G
H - I - J - K - L - M - N - O - P
Q - R - S
T - U - V
W - X - Y and Zee
Now I know my A - B - C
Won't you come and sing with me?""")
f.close()

!ls -l

f = open("test2.txt","w")
f.write("""A - B - C - D - E - F - G
H - I - J - K - L - M - N - O - P
Q - R - S
T - U - V
W - X - Y and Zee
Happy, happy, I'm happy
I can sing my ABC""")
f.close()

def main():
  file1 = input("比較する1つ目のファイル名を入力してください：")
  file2 = input("比較する2つ目のファイル名を入力してください：")
  f1 = open(str(file1),"r")
  text1 = f1.read()
  f1.close()
  f2 = open(str(file2),"r")
  text2 = f2.read()
  f2.close()
  if text1 == text2:
    print(str(file1)+"と"+str(file2)+"は内容が同じです")
  if text1 != text2:
    print(str(file1)+"と"+str(file2)+"は内容が違います")




main()