# -*- coding: utf-8 -*-
"""ex04_4_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wfwus8C2OGbj2HXkCRl1w83A0N6kzQV5
"""

f = open("sample1.py","w")
f.write("""a = 3
b = 2
# この行は空行
x = a / b
print( "a / b == {:f}".format( x ) )
# {:f}はformatメソッドの引数の値を浮動小数点数として解釈する""")
f.close()

f = open("sample2.py","w")
f.write("""c = 3.0
d = 0.02e2　　# 指数表示 0.02×( 10 の 2 乗 )
# この行は空行
print("c={:f}, d={:f}".format(c,d))""")
f.close()

def main():
  File = input("ファイル名を入力してください：")
  print("コメント部分削除前のファイルの内容:")
  f = open(str(File),"r")
  text = f.read()
  f.close()
  print(text)
  print("   ")
  print("削除した結果:")
  Filedel=File
  fdel = open(str(Filedel), "r")
  lines = fdel.readlines()
  fdel.close()
  for i, line in enumerate(lines):
    target = "#"
    idx = line.find(target)
    r = line[0:idx]
    print(r)

main()
main()