# -*- coding: utf-8 -*-
"""ex05_3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OtQCUIbmLycT0ewKheixMfd9HXs7iMJG
"""

A = [[0,0],[0,0]]
revA = [[0,0],[0,0]]
detA = 0
def rever(A,revA):
  detA = float(A[0][0])*float(A[1][1])-float(A[0][1])*float(A[1][0])
  if detA != 0:
    revA = [[(1/detA)*A[1][1],-(1/detA)*A[0][1]],[-(1/detA)*A[1][0],(1/detA)*A[0][0]]]
    outout(revA)
  return detA

def inin():
 print("元の行列を入力してください")
 A[0][0] = float(input("A[0][0]:"))
 A[0][1] = float(input("A[0][1]:"))
 A[1][0] = float(input("A[1][0]:"))
 A[1][1] = float(input("A[1][1]:"))
 print(A[0][0],A[0][1])
 print(A[1][0],A[1][1])

def outout(revA):
  print("逆行列は以下の通り")
  print(revA[0][0],revA[0][1])
  print(revA[1][0],revA[1][1])

def main():
  inin()
  if  rever(A,revA) == 0:
    print("逆行列は存在しない")


main()

main()

