# -*- coding: utf-8 -*-
"""ex05_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fI34mm6czJoA75mj3DRAokNpVEoIzhw7
"""

def count():
  c = [0,0,0,0,0,0,0,0,0,0]
  print("0～9の任意の整数を入力してください")
  while True:
      try:
          a = input("")
          for i in range(0,9):
            i == a
            c[int(a)] += 1
      except EOFError:
          break

  for i in range(0,10):
    print(str(i) + "の個数は" + str(c[i]//9))


count()