# -*- coding: utf-8 -*-
"""ex05_4_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lFOOgj2kTw8iRe57OfunsQtRuGhEjE4
"""

vac1 = [0,0,0,0,0,0,0,0,0,0]
vac2 = [0,0,0,0,0,0,0,0,0,0]
def main():
  n = int(input("ベクトルの次数n (最大10)="))
  print("ベクトル１の入力")
  for i in range (0,n):
   vac1[i] = input("")
  print("ベクトル2の入力")
  for i in range (0,n):
   vac2[i] = input("")
  print("内積="+str(inseki(n)))

def inseki(n):
  result = 0
  for i in range (0,n):
   result += float(vac1[i])*float(vac2[i])
  return result


main()