# -*- coding: utf-8 -*-
"""ex05_1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZnFHTwim6Hk6fmIX3pwV68UPV8RCpdT
"""

def maxf(listx):
    for i in range(0,len(listx)-1):
      if listx[i] > listx[i+1]:
        max = listx[i]
    return  (max)

listx = [2,4,5,6,6,7,8,8,8,9,77,6]
print(listx)
print("最大値")
maxf(listx)