# -*- coding: utf-8 -*-
"""ex05_a1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etAPqXGoqzSCiRlUXsPW4pqCXK0Af8G2
"""

import math
vac1 = [0,0,0,0,0,0,0,0,0,0]
vac2 = [0,0,0,0,0,0,0,0,0,0]
def main():
  n = int(input("ベクトルの次数n (最大10)="))
  print("ベクトル１の入力")
  for i in range (0,n):
   vac1[i] = input("")
  print("ベクトル2の入力")
  for i in range (0,n):
   vac2[i] = input("")
  cos = inseki(n) / ((vac(vac1,n)) * (vac(vac2,n)))
  acos = math.acos(cos)
  print("φ＝"+str(rad(acos)))

def inseki(n):
  result = 0
  for i in range (0,n):
   result += float(vac1[i])*float(vac2[i])
  return result

def vac(vac,n):
  bigvec = 0
  for i in range (0,n):
   bigvec += float(vac1[i])**2
  vec = math.sqrt(bigvec)
  return vec

def rad(raj):
  deg = raj * 180 / math.pi
  return deg

main()