# -*- coding: utf-8 -*-
"""ex06_4_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1fAALfKNYp3Ngjwt63gqYsiSEcc1ofX
"""

import csv
class Item:
    def __init__(self,number:int, name: str,score:int):
        self.number = number
        self.name = name
        self.score = score
class ItemList:
    def __init__(self):
        self.item = []
    def aditem(self,number:int,name:str,score:int):
        self.item.append(Item(number, name, score))
    def csvreader(self,filename:str):
        with open(filename,'r') as f:
            csvr = csv.reader(f)
            next(csvr)
            for row in csvr:
                number = int(row[0])
                name = str(row[1])
                score = int(row[2])
                self.aditem(number,name,score)
    def outout(self, newfile:str):
       f = open(newfile,'w')
       for item in self.item:
         f.write(f"{item.number:4},{item.name:16},{item.score:3}\n")
    def highsc(self,item,n):
        looktime = 0
        swich = 0
        for i in range(0,n):
            a = i
            for j in range(i+1,n):
                looktime += 1
                if item[j].score > item[a].score or(item[j].score == item[a].score and item[j].number<item[a].number):
                    a = j
            if a!=i:
                swich += 1
            item[i],item[a] = item[a],item[i]
        print(f"比較回数 = {looktime}, 入れ換え回数 = {swich}")
        return item
def main():
  item_list = ItemList()
  while True:
    n = input("ファイルの中のデータ数を教えて（8or288or2240)")
    if n  in ["8" , "288" ,"2240"]:
     item_list.csvreader("data_"+str(n)+".csv")
     sorteditem = item_list.highsc(item_list.item, len(item_list.item))
     item_list.item = sorteditem
     output_filename = "outputno2_"+str(n)+".txt"
     print(f"出力ファイル名: {output_filename}")
     item_list.outout(output_filename)
     break
    else:
     print("8or288or2240のデータ数を入力してください")

main()

main()

main()