# -*- coding: utf-8 -*-
"""ex06_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdbfyy38bG06q_Tg9O0eL4a-bAWTklsY
"""

import csv

class Item:
    def __init__(self, number: int, name: str, score: int):
        self.number = number
        self.name = name
        self.score = score

class ItemList:
    def __init__(self):
        self.item = []
    def aditem(self,number:int,name:str,score:int):
        self.item.append(Item(number, name, score))
    def csvreader(self,filename:str):
        with open(filename,'r') as f:
            csvr = csv.reader(f)
            next(csvr)
            for row in csvr:
                number = int(row[0])
                name = str(row[1])
                score = int(row[2])
                self.aditem(number,name,score)
    def outout(self):
       for item in self.item:
         print(f"{item.number:4},{item.name:16},{item.score:3}")
    def highsc(self,item,n):
        for i in range(n):
            a = i
            for j in range(i+1, n):
                if item[j].score > item[a].score:
                    a = j
            item[i], item[a] = item[a], item[i]
        return item
def main():
  item_list = ItemList()
  while True:
    n = input("ファイルの中のデータ数を教えて（8or288or2240)")
    if n  in ["8" , "288" ,"2240"]:
     item_list.csvreader("data_"+str(n)+".csv")
     sorteditem = item_list.highsc(item_list.item, len(item_list.item))
     item_list.item = sorteditem
     item_list.outout()
     break
    else:
     print("8or288or2240のデータ数を入力してください")

main()

main()

main()