# -*- coding: utf-8 -*-
"""ex06_1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVUaFfWVqx6cWOPH_694sPee7x1r4iGM
"""

import csv
class Item:
  def __init__ (self,number:int, name:str,score:int):
   self.number = number
   self.name = name
   self.score = score
class ItemList:
  def __init__(self):
    self.item = []
  def aditem(self,number:int,name:str,score:int):
    self.item.append(Item(number,name,score))
  def csvreader(self,filename:str):
    with open(filename,'r')as f:
     csvr = csv.reader(f)
     for row in csvr:
       number = (row[0])
       name = str(row[1])
       score = int(row[2])
       self.aditem(number,name,score)
  def outout(self):
    for item in self.item:
      print(f"{item.number:4},{item.name:16},{item.score:3}")

item_list = ItemList()
item_list.csvreader('data_8.csv')
item_list.outout()

item_list = ItemList()
item_list.csvreader('data_288.csv')
item_list.outout()

item_list = ItemList()
item_list.csvreader('data_2240.csv')
item_list.outout()