# -*- coding: utf-8 -*-
"""ex07_a2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnUd7Agr-lTK3vWFHm0LRV0Y6sDvtu4p
"""

def main():
  A = [9,1,3,7,0,5,4,2,8,6]
  while True:
    a = A[:]
    m = int(input("開始位置を入力してくださいm="))
    n = int(input("終了位置を入力してくださいn="))
    if m==0 and n==0:
     break
    changea = bubblesort(a,m,n)
    print(changea)
def bubblesort(List,m,n):
    n += 1
    for i in range(m,n):
      for j in range(m,n+m-i-1):
       if List[j] > List[j+1]:
          List[j], List[j+1] = List[j+1], List[j]
    return List

main()