# -*- coding: utf-8 -*-
"""ex07_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ynjqVYuGyuQpFS2Ie5X4vc1PmJxz-NnC
"""

import csv           #csvファイルを用いるための設定
looktime = 0
swich = 0

class Item:          #クラス、Itemの定義
  def __init__ (self, number:int, name:str, score:int):#クラスの設定
   self.number = number       #生徒番号の設定
   self.name = name           #名前の設定
   self.score = score         #成績の設定

def aditem(item_list,number:int,name:str,score:int):#クラスに要素追加関数
  item_list.append(Item(number,name,score))

def csvreader(filename:str, item_list):
  with open(filename,'r') as f:
    csvr = csv.reader(f)
    next(csvr)
    for row in csvr:
      number = int(row[0])
      name = str(row[1])
      score = int(row[2])
      aditem(item_list, number, name, score)

def outout(item_list,newfile):
  global looktime,swich
  looktime = 0
  swich = 0
  alist = quicksort(item_list,0, len(item_list)-1)
  f = open(newfile,"w")
  quicksort(item_list,0, len(item_list)-1)
  print("比較回数="+str(looktime),"入れ替え回数="+str(swich))
  for item in alist:
    f.write(f"{item.number:4},{item.name:16},{item.score}\n")
  print("出力ファイル名："+str(newfile))

def quicksort(a:list, left:int,right:int):
    global looktime,swich
    if left < right:
        i, j = left, right
        x = a[(left + right) // 2].score
        while True:
            while(a[i].score < x):
                looktime += 1
                i += 1
            while(x < a[j].score):
                looktime += 1
                j -= 1
            if (i <= j):
                if i < j:
                    swich += 1
                    a[i], a[j] = a[j], a[i]
                i += 1
                j -= 1
            if i > j:
                break
        if left < j:
            quicksort(a, left, j)
        if i < right:
            quicksort(a , i, right)
        return a
item_list = []
csvreader('data_8.csv', item_list)
outout(item_list,"output_8.txt")

item_list = []
csvreader('data_288.csv', item_list)
outout(item_list,"output_288.txt")

item_list = []
csvreader('data_2240.csv', item_list)
outout(item_list,"output_2240.txt")