# -*- coding: utf-8 -*-
"""ex07_1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqaQNbEn-Kh809ANbkfp7_IKxH_DdCVG
"""

import csv

class Item:
  def __init__ (self, number:int, name:str, score:int):
   self.number = number
   self.name = name
   self.score = score

def aditem(item_list,number:int,name:str,score:int):
  item_list.append(Item(number,name,score))

def csvreader(filename:str, item_list):
  with open(filename,'r') as f:
    csvr = csv.reader(f)
    next(csvr)
    for row in csvr:
      number = int(row[0])
      name = str(row[1])
      score = int(row[2])
      aditem(item_list, number, name, score)

def outout(item_list):
  alist = quicksort(item_list,0, len(item_list)-1)
  for item in alist:
    print(f"{item.number:4},{item.name:16},{item.score:3}")

def quicksort(a:list, left:int,right:int):
    if left < right:
        i, j = left, right
        x = a[(left + right) // 2].score
        while True:
            while(a[i].score < x):
                i += 1
            while(x < a[j].score):
                j -= 1
            if (i <= j):
                if i < j:
                    a[i], a[j] = a[j], a[i]
                i += 1
                j -= 1
            if i > j:
                break
        if left < j:
            quicksort(a, left, j)
        if i < right:
            quicksort(a , i, right)
        return a
item_list = []
csvreader('data_8.csv', item_list)
outout(item_list)

item_list = []
csvreader('data_8.csv', item_list)
outout(item_list)

item_list = []
csvreader('data_288.csv', item_list)
outout(item_list)

item_list = []
csvreader('data_2240.csv', item_list)
outout(item_list)

