# -*- coding: utf-8 -*-
"""ex07_3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bcj790O_E0x44ZdHGtBDLHN7C53Kl2fK
"""

import csv

class Item:
  def __init__ (self, number:int, name:str, score:int):
   self.number = number
   self.name = name
   self.score = score

def aditem(item_list,number:int,name:str,score:int):
  item_list.append(Item(number,name,score))

def csvreader(filename:str, item_list):
  with open(filename,'r') as f:
    csvr = csv.reader(f)
    next(csvr)
    for row in csvr:
      number = int(row[0])
      name = str(row[1])
      score = int(row[2])
      aditem(item_list, number, name, score)

def outout(item_list,newfile):
  alist = quicksort(item_list,0, len(item_list)-1)
  f = open(newfile,"w")
  for item in alist:
    f.write(f"{item.number:4},{item.name:16},{item.score}\n")
  print("入力ファイル名："+str(filename))
  print("出力ファイル名："+str(newfile))

def quicksort(a:list, left:int,right:int):
    if left < right:
        i, j = left, right
        x = a[(left + right) // 2].score
        y = a[(left + right) // 2].number
        while True:
            while(a[i].score < x or (a[i].score == x and a[i].number < y)):
                i += 1
            while(x < a[j].score or (a[j].score == x and a[j].number > y)):
                j -= 1
            if (i <= j):
                if i < j:
                    a[i], a[j] = a[j], a[i]
                i += 1
                j -= 1
            if i > j:
                break
        if left < j:
            quicksort(a, left, j)
        if i < right:
            quicksort(a , i, right)
        return a

item_list = []
filename = 'data_8.csv'
csvreader(filename, item_list)
outout(item_list,"outputno73_8.txt")

item_list = []
filename = 'data_288.csv'
csvreader(filename, item_list)
outout(item_list,"outputno73_288.txt")

item_list = []
filename = 'data_2240.csv'
csvreader(filename, item_list)
outout(item_list,"outputno73_2240.txt")