# -*- coding: utf-8 -*-
"""ex08_3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-HWf47MsAUYrihva9vxcUPGskDvRr--
"""

def main():
 print("整数nを代入してください")
 n = int(input("n:"))
 print(str(n)+"!=")
 print("再帰:"+str(saiki(n)))
 loop(n)

def loop(n):
  a = 1
  for i in range(1,n+1):
   a *= i
  print("ループ:"+str(a))

def saiki(n):
  if n == 0:
    return 1
  else:
    return n*saiki(n-1)


main()