# -*- coding: utf-8 -*-
"""ex08_1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oz85gbMVOqwPC1CpMwGm5DN31lfgNjVH
"""

def main():
 k = int(input("kの値を入力してください"))
 n = int(input("nの値を入力してください"))
 if 0 >= k or k>=n:
  print("0<k<nではありません")
 else:
  a = f(n,k)
  print(a)

def f(n,k):
  if k == 0:
   a = 1
   return a
  elif k ==n:
   a =1
   return a
  else:
   return f(n-1,k-1)+f(n-1,k)

main()#0 < k < n の場合.
main()#k=0
main()#k=n
main()#k<0