# -*- coding: utf-8 -*-
"""ex08_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4znkSSodicW80W70cLH7u8yFGnmwuNf
"""

def main():
 list4 =[0,1,4,-10]
 print("リストの中身："+ str(list4))
 for i in range(0,4):
  n = list4[i]
  print("n:"+str(n))
  print("f(n):"+str(f(n)))
  print("g(n):"+str(g(n)))

def f(n):
  if n <= 1:
    return 1
  else:
   return n *g(n-1)
def g(n):
  if n==0:
   return 1
  else:
   return n+f(n-1)

main()