# -*- coding: utf-8 -*-
"""ex09_1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19E4kcMMeguRmQASwAB4d08CfM1isTjVz
"""

data=[
    [8,8,8,8,8,8,8,8,8,8],
    [8,1,0,0,8,8,0,0,0,8],
    [8,0,8,0,0,0,0,8,0,8],
    [8,0,8,8,8,0,8,8,0,8],
    [8,0,0,8,8,0,0,8,0,8],
    [8,8,0,0,8,0,8,8,0,8],
    [8,0,8,0,8,0,0,8,0,8],
    [8,0,0,0,8,8,0,0,0,8],
    [8,8,8,0,0,0,0,8,0,8],
    [8,8,8,8,8,8,8,8,1,8]
]

for row in data:
    for cell in row:
      if cell == 0:
        print("  ",end="")
      elif cell ==1:
        print("〇",end="")
      elif cell ==8:
        print("■",end="")
    print()