# -*- coding: utf-8 -*-
"""ex09_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6qdQafDZFbzO8_snRgseeJDUb1IO6QL
"""

def LIST(pp, M, N):#再帰的に組み合わせを生成する関数
    if N == 0:
        return [pp]
    retu = []
    for i in range(1, M + 1):
        retu += LIST(pp+[i],M,N-1)
    return retu

print("1 から M までを並べる 1 桁の正数 M を入力してください")
M = int(input("M="))
print("1 から M までの数を N 個を並べる 正数 N を入力してください")
N = int(input("N="))
makelist = LIST([], M, N)
nagasa = 0
for i in makelist[0]:
    nagasa += len(str(i)) + 1
max = 78 // nagasa
nagasa -= 1
for i in range(0, len(makelist), max):
    pat = makelist[i:i+max]
    line = ''
    for i in pat:
        for num in i:
            line += str(num) + ' '
        line = line[0:-1] + '  '
    print(line)