# -*- coding: utf-8 -*-
"""ex09_a1_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cODzI6cMN0AkFhAHlb_5eBzE2S4czfZS
"""

def new(elements):
    if len(elements) == 1:
        return [elements]
    List = []
    for i in range(len(elements)):
        c = elements[i]
        remaining = elements[:i] + elements[i+1:]
        for perm in new(remaining):
            List.append([c] + perm)
    return List

def keisan():
    digits = '123456789'
    out = list(digits)
    aaa = new(out)
    results = []
    for perm in aaa:
        num1 = int(''.join(perm[:5]))
        num2 = int(''.join(perm[5:]))
        if num1 / num2 == 13:
            results.append((num1, num2))
    return results

results = keisan()
for result in results:
    print(f"{result[0]} / {result[1]} = 13")