# -*- coding: utf-8 -*-
"""ex09_a3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoP3q7cpaT8CTkJyWcFZz718d0SOWrtb
"""

def main():
    a = "334/334"
    n = int(input("任意の自然数（「0」）を含まないを入力してください："))
    for i in range(n-1):
      a += "+334/334"
    print(str(n),"=",a)

main()
main()
main()
main()