# -*- coding: utf-8 -*-
"""ex09_3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NC4st5uOvptAYcrNuYauthEh5z0INFzi
"""

for i in range(1, 10):
    op[i] = 0
while op[1] < 2:
    s = 0
    n = 0
    sign = 1
    for i in range(1, 10):
        if op[i] == 0:
            n = 10 * n + i
        else:
            s += sign * n
            n = i
            if op[i] == 1:
                sign = -1
            else:
                sign = 1
    s += sign * n
    if s == 100:
        result = ""
        for i in range(1, 10):
            if op[i] == 1:
                result += "－"
            elif op[i] == 2:
                result += "＋"
            result += str(i)
        print(result+"=100")
    i = 9
    op[i] += 1
    while i > 1 and op[i] == 3:
        op[i] = 0
        i -= 1
        op[i] += 1