# -*- coding: utf-8 -*-
"""ex09_a1_1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11En3ovQYVR5SVnowlhwJAie8EoGqZQb7
"""

op = [0]*10
for i in range(1, 10):
    op[i] = 0
while op[9] < 2:
    s = 0
    n = 0
    sign = 1
    for i in range(9, 0, -1):
        if op[i] == 0:
            n = 10 * n + i
        else:
            s += sign * n
            n = i
            if op[i] == 1:
                sign = -1
            else:
                sign = 1
    s += sign * n
    if s == 100:
        result = ""
        for i in range(9, 0, -1):
            if op[i] == 1:
                result += "－"
            elif op[i] == 2:
                result += "＋"
            result += str(i)
        print(result+"=100")
    i = 1
    op[i] += 1
    while i < 9 and op[i] == 3:
        op[i] = 0
        i += 1
        op[i] += 1