# -*- coding: utf-8 -*-
"""ex10_a2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136iNiPGyHjkDCeeJ4Zo1bUk65mjZxjqH
"""

def minc(A, B, C, x):
    coins = [A, B, C, 1]
    coinc = 0
    remain = x
    for coin in coins:
        if remain == 0:
            break
        numc = remain // coin
        coinc += numc
        remain -= numc * coin

    return coinc

A = 100
B = 10
C = 5
x = 127
print("最小枚数は"+str(minc(A, B, C, x))+"枚")

A = 50
B = 40
C = 7
x = 127
print("最小枚数は"+str(minc(A, B, C, x))+"枚")