# -*- coding: utf-8 -*-
"""ex10_a1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PZ38oNxIMwyAN8gCGog0tigBMT2wG7L
"""

class Bucket:
    def __init__(self, cap):
        self.cap = cap
        self.current = 0
    def fill(self):
        self.current = self.cap
    def drop(self):
        self.current = 0

    def move(self, other):
        total = self.current + other.current
        other.current = min(total, other.cap)
        self.current = total - other.current

def measure_water(A, B, C):
    buA = Bucket(A)
    buB = Bucket(B)
    operations = []

    while buA.current != C and buB.current != C:
        if buA.current == 0:
            buA.fill()
            operations.append("Fill( A )")
        elif buB.current == B:
            buB.drop()
            operations.append("Drop( B )")
        else:
            buA.move(buB)
            operations.append("Move( A, B )")

    return operations

A = 5
B = 3
C = 4
print(measure_water(A, B, C))