# -*- coding: utf-8 -*-
"""ex10_3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UfQw6kp3GxfnDFFkQ6XdCeAC5X3kBUo
"""

from0 = [1, 2, -1]
from1 = [0, 2, 3, 4, -1]
from2 = [0, 1, 3, -1]
from3 = [1, 2, 4, -1]
from4 = [1, 3, -1]
roads = [from0, from1, from2, from3, from4]

def way(a, path, checklist):
    path.append(a)
    if a == 4:
        print(path)
    else:
       for next in roads[a]:
        if next == -1:
           break
        if next not in checklist:
           checklist.add(next)
           way(next, path.copy(), checklist.copy())
           checklist.remove(next)
    path.pop()
way(0, [], {0})