# -*- coding: utf-8 -*-
"""ex10_1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZpVH6B80wkZPexC42jCllG3Z27pLL-n
"""

def keisan(a,b,c,d):
  if 10*a+b==3*(10*c+d) and a!=b and c!=d and a!=c and b!=d and a!=d and b!=c:
    print(10*a+b,10*c+d)
for a in range(1,10):
  for b in range(1,10):
    for c in range(1,10):
      for d in range(1,10):
        keisan(a,b,c,d)