# -*- coding: utf-8 -*-
"""ex10_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-j3s6cktJV8SGm0GkW7ScGu8cawIowIT
"""

class Item:
    def __init__(self, name, weight):
        self.name = name
        self.weight = weight
items = [Item('A', 7), Item('B', 4), Item('C', 5), Item('D', 6), Item('E', 3)]
max_load = 15
def try_item(i,dw,ditems):
    if dw == max_load:
        print(' + '.join(f'{item.name}:{item.weight}t' for item in ditems))
        return
    if i == len(items) or dw > max_load:
        return
    try_item(i + 1, dw,ditems)
    try_item(i + 1, dw+ items[i].weight, ditems + [items[i]])

try_item(0, 0, [])