# -*- coding: utf-8 -*-
"""ex11_a2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjqY1EUEwW9Ji-rh_QQ5nJtI0sWfPi-8
"""

import re
from bisect import bisect_left

def count_words_linear(filename):
    with open(filename, 'r') as f:
        text = f.read().lower()
    words = re.findall(r'\b\w+\b', text)
    counts = {}
    for word in words:
        if word not in counts:
            counts[word] = 1
        else:
            counts[word] += 1
    return counts

def count_words(filename):
    with open(filename, 'r') as f:
        text = f.read().lower()
    words = sorted(re.findall(r'\b\w+\b', text))
    word_counts = {}
    i = 0
    while i < len(words):
        word = words[i]
        count = 1
        while i + 1 < len(words) and words[i + 1] == word:
            i += 1
            count += 1
        word_counts[word] = count
        i += 1
    return word_counts


def output(word_counts):
    for word, count in word_counts.items():
        print(f"{word}: {count}")

print("Coll_of_ES_EPs.txtファイルの文字数は:")
word_counts_linear = count_words_linear("Coll_of_ES_EPs.txt")
output(word_counts_linear)

print("Dep_of_M-P-EE-CS.txtファイルの文字数は:")
word_counts_binary = count_words("Dep_of_M-P-EE-CS.txt")
output(word_counts_binary)