# -*- coding: utf-8 -*-
"""ex11_3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8Be9q4Lr1udnalecEPla4IOX8hlIhUY
"""

class Player:                                   #クラスの定義
    def __init__(self, number, name, profile):  #クラスの型を（登録番号、名前、プロファイル）と設定
        self.number = number                    #登録番号のクラス設定
        self.name = name                        #名前のクラス設定
        self.profile = profile                  #プロフィールのクラス設定

def senkeilist(filename):               # 線形ファイルを作成する関数  
    players = []                        #選手の情報を格納するファイル
    with open(filename, 'r', encoding='utf-8') as f: #ファイルをutf-8仕様で読み取り専用で開く
        lines = f.readlines()                        #変数linesにファイル内容を一行ずつ格納
        for line in lines:                           #linesのそれぞれの行について
            data = line.split()                      #変数データに1行を分割した文字列を格納
            player = Player(int(data[0]), data[1], ' '.join(data[2:])) #変数playerにlines一行ずつのクラスを格納
            players.insert(0, player)                                  #変数playersに上で定義したクラスを挿入
    return players                                                     #playersに値を返す

def outputlist(players):              #ファイル内を出力する関数
    for player in players:            #クラスplayer中のplayersに対して
        print(f"{player.number:2d} {player.name} {player.profile}")   #データを出力

def delete_player(players, number):     #指定された選手を削除する関数
    for i in range(len(players)):       #ファイルに含まれているplayersの数だけ実行
        if players[i].number == number: #その登録番号が指定された番号と一致する時
            print("---削除しました---")  #削除しましたというメッセージの出力
            del players[i]              #playersのリストから削除する
            return                      #戻り値なしで関数終了
    print("---該当者はいません---")      #指定された番号が登録番号にない時該当者はいませんのメッセージを出力
   
def main():                               #main（）関数
    players = senkeilist("Zac_Japan.txt") #ファイル名を指定して線形リスト関数を呼び出す
    outputlist(players)                   #outputlist関数を呼び出してリスト内の内容を表示

    while True:                          #条件が正しい時は継続
        number = int(input("削除する登録番号は？ ")) #削除する登録番号を変数numberに格納
        if number == 0:                             #numberの値が0の時
            print("プログラムを終了します")          #プログラム終了のメッセージを出力
            break                                   #繰り返しのループから抜ける

        delete_player(players, number)              #delete_player関数を呼び出して指定番号の内容を削除
        outputlist(players)                         #outputlist関数を呼び出してファイル内を出力

main()                                              #

main()

main()

main()

main()