# -*- coding: utf-8 -*-
"""ex11_a1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXt4BOkVNgEeRjvPaSyzTLPTHNfUR7Cn
"""

class Player:
    def __init__(self, number, name, profile):
        self.number = number
        self.name = name
        self.profile = profile

def senkeilist(filename):
    players = []
    with open(filename, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            data = line.split()
            player = Player(int(data[0]), data[1], ' '.join(data[2:]))
            players.append(player)
    players.sort(key=lambda player: player.number)
    return players

def outputlist(players):
    for player in players:
        print(f"{player.number:2d} {player.name} {player.profile}")

players = senkeilist("Zac_Japan.txt")
outputlist(players)