# -*- coding: utf-8 -*-
"""ex11_1_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXyzLor8gMdJGpPag_uQ-_ld2FJNGck4
"""

class Player:
  def __init__(self,number,name,profile):
      self.number = number
      self.name = name
      self.profile = profile

def senkeilist(filename):
    players = []
    with open(filename,'r',encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            data = line.split()
            player = Player(int(data[0]), data[1], ' '.join(data[2:]))
            players.insert(0, player)
    return players

def outputlist(players):
    for player in players:
        print(f"{player.number:2d} {player.name} {player.profile}")

players = senkeilist("Zac_Japan.txt")
outputlist(players)