# -*- coding: utf-8 -*-
"""ex11_3_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8Be9q4Lr1udnalecEPla4IOX8hlIhUY
"""

class Player:                                   #クラスの定義
    def __init__(self, number, name, profile):  #クラスの型を（登録番号、名前、プロファイル）と設定
        self.number = number                    #登録番号のクラス設定
        self.name = name                        #名前のクラス設定
        self.profile = profile                  #プロフィールのクラス設定

def senkeilist(filename):               #          
    players = []                        #
    with open(filename, 'r', encoding='utf-8') as f: #
        lines = f.readlines()                        #
        for line in lines:                           #
            data = line.split()                      #
            player = Player(int(data[0]), data[1], ' '.join(data[2:]))#
            players.insert(0, player)                                 #
    return players                                                    #

def outputlist(players):              #
    for player in players:            #
        print(f"{player.number:2d} {player.name} {player.profile}")   #

def delete_player(players, number):     #
    for i in range(len(players)):       #
        if players[i].number == number: #
            print("---削除しました---")  #
            del players[i]              #
            return                      #
    print("---該当者はいません---")      #
   
def main():                               #
    players = senkeilist("Zac_Japan.txt") #
    outputlist(players)                   #

    while True:                          #
        number = int(input("削除する登録番号は？ ")) #
        if number == 0:                             #
            print("プログラムを終了します")          #
            break                                   #

        delete_player(players, number)              #
        outputlist(players)                         #

main()                                              #

main()

main()

main()

main()