# -*- coding: utf-8 -*-
"""ex11_2_2364092

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1wJ73gnDnvOsvOYEq78jrrpw9P-VWNM
"""

class Player:
    def __init__(self, number, name, profile):
        self.number = number
        self.name = name
        self.profile = profile

def senkeilist(filename):
    players = []
    with open(filename, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            data = line.split()
            player = Player(int(data[0]), data[1], ' '.join(data[2:]))
            players.insert(0, player)
    return players

def search(players, number):
    for player in players:
        if player.number == number:
            return player
    return None

def main():
    players = senkeilist("Zac_Japan.txt")

    while True:
        number = int(input("探索する登録番号は？ "))
        if number == 0:
            print("プログラムを終了します")
            break

        player = search(players, number)
        if player is None:
            print("該当する選手はいません")
        else:
            print(f"{player.number} {player.name} {player.profile}")

main()