# -*- coding: utf-8 -*-
"""No3-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsg_qawITAq7yvbjjqG6oLYWTRZt6W5h
"""

def main():
  global result
  global num
  result = 0
  num = 0
  n = 1
  while n>=0:
    n = int(input("n:"))
    fn(n)
  return

def fn(n):
  global num
  global result
  if n == num:
    print('再計算する必要はありません')
    print(result)
  elif n > 0:
    result = 0
    num = n
    while n>0:
      result += n*n
      n -= 1
    print(result)

main()

